type DataType = {
    id: number,
    title: string,
    img: string,
    description: string,
    features: {
        id: number
        feature: string,
        available: boolean
    }[];
    link: string;
}[]
export const schoolData: DataType = [
    {
        id: 1,
        title: "Product Management",
        img: "/images/schools/2.png",
        description: "Learn how to build and launch successful products from ideation to execution.",
        features: [],
        link: "https://wa.link/3fphdr",
    },
    {
        id: 2,
        title: "Technical PM (TPM)",
        img: "/images/schools/3.png",
        description: "Master the intersection of tech and business with hands-on TPM skills.",
        features: [],
        link: "https://wa.link/3fphdr",
    },
    {
        id: 3,
        title: "UX/UI Design Fundamentals",
        img: "/images/schools/4.png",
        description: "Understand user experience and interface design to create intuitive products.",
        features: [],
        link: "https://wa.link/3fphdr",
    },
    {
        id: 4,
        title: "No-Code Development",
        img: "/images/schools/6.png",
        description: "Build apps and websites without coding using powerful no-code tools.",
        features: [],
        link: "https://wa.link/3fphdr",
    },
    {
        id: 5,
        title: "Web Development",
        img: "/images/schools/7.png",
        description: "Learn the core skills for front-end and back-end web development.",
        features: [],
        link: "https://wa.link/3fphdr",
    },
    {
        id: 6,
        title: "React.js for Beginners",
        img: "/images/schools/8.png",
        description: "Get hands-on experience building interactive websites with React.js.",
        features: [],
        link: "https://wa.link/3fphdr",
    },
    {
        id: 7,
        title: "Software Engineering",
        img: "/images/schools/9.png",
        description: "Learn the fundamentals of software development and best coding practices.",
        features: [],
        link: "https://wa.link/3fphdr",
    },
    {
        id: 8,
        title: "AI for Beginners – Using AI",
        img: "/images/schools/10.png",
        description: "Discover how to use AI tools to boost productivity and automate tasks.",
        features: [],
        link: "https://wa.link/3fphdr",
    },
    {
        id: 9,
        title: "Data Analytics for Beginners",
        img: "/images/schools/11.png",
        description: "Learn how to analyze data, create dashboards, and make data-driven decisions.",
        features: [],
        link: "https://wa.link/3fphdr",
    },
    {
        id: 10,
        title: "Website Design Fundamentals",
        img: "/images/schools/12.png",
        description: "Understand design principles to create visually appealing websites.",
        features: [],
        link: "https://wa.link/3fphdr",
    },
    {
        id: 11,
        title: "Mobile App Development",
        img: "/images/schools/13.png",
        description: "Learn how to develop mobile applications for Android and iOS.",
        features: [],
        link: "https://wa.link/3fphdr",
    },
    {
        id: 12,
        title: "Product Dev & MVP Launch",
        img: "/images/schools/14.png",
        description: "Turn your idea into a minimum viable product (MVP) and launch successfully.",
        features: [],
        link: "https://wa.link/3fphdr",
    },
];
